backend:
  name: github
  repo: git@github.com:MarinMoLing/MarinMoLing.github.io.git  # 你的 GitHub 仓库
  branch: main                       # 你的主分支，一般是 main 或 master

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "source/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "posts"
    label: "文章"
    folder: "source/_posts"
    create: true
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "缩略图", name: "thumbnail", widget: "image", required: false }
      - { label: "内容", name: "body", widget: "markdown" }
  - name: "pages"
    label: "页面"
    folder: "source/about"
    create: true
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "内容", name: "body", widget: "markdown" }
